ExchangeUnion/xud-docker

- xud.sh
echo missing, caused script to exit with syntax error
> fix: docker check echo

- .gitignore
- .travis.yml
- tests/Vagrantfile
- tests/init.sh
- tests/run_test.sh
- tests/testnet.exp
- xud.sh
Resolve https://github.com/ExchangeUnion/xud-docker/issues/18
> Add some vagrant tests and Travis-CI support

- status.sh
> Refine status script

- xud-testnet/docker-compose.yml
- xud.sh
> Fix litecoind broken data crash

- xud-testnet/docker-compose.yml
Quickly did that
Closes https://github.com/ExchangeUnion/xud-docker/issues/57
> fix: add lndbtc port 9735 and lndltc port 10735

- .gitignore
- images/raiden/Dockerfile
- images/raiden/a.py
- images/raiden/checksum.py
- images/raiden/configWriter.py
- images/raiden/entrypoint.sh
This PR closes #65 and addresses the Raiden matrix servers mentioned in #33. I wrote a little Python script that is executed when the image is started to set the required config variables. My Python is not that good so please have a close look  at the script @reliveyy.
> feat: write Raiden config

- setup.sh
> adds upgrade prompt 

- images/xud-simnet/entrypoint.sh
- images/xud/entrypoint.sh
> fix(xud): disable xud config rewriting

- setup.sh
> separated log files per network

- README.md
This PR adds some documentation for developers looking to add features to the repository.
> Add documentation for developers

- init.sh
> fix(report): xud-docker.log could be empty sometimes

- init.sh
This PR is a follow up one of #137 and fixes the aliases on mainnet.
> fix: aliases on mainnet

- init.sh
Resolves #92 
Fixed the issue by just hiding first line of every xucli outputs
> fix: xud getenv warning

- init.sh
- main.sh
- setup.sh
- status.py
Resolves #89 
Based on xud-simnet's `xud-simnet-channels` script. It will check whether BTC and LTC channels is open or not. If channels are not open yet then xudctl will block and wait until channels are ready. In the meantime xudctl will print dots in screen like xud-simnet. Users can type `Ctrl-C` to stop waiting but next time when users execute xud script and if the channels are still not ready then dots will continute printing.
> feat: add xudctl launch checks

- images/lnd/supervisord.conf
- images/xud/Dockerfile
- images/xud/entrypoint.sh
- images/xud/xud.conf
- main.sh
- setup.sh
- xucli_create_wrapper.py
Resolves #63 
* Add xud master password support (xucli create)
> feat: xud master password

- images/lnd-simnet/unlocker.sh
> fix: Neutrino sync on simnet

- images/raiden/Dockerfile
- images/raiden/supervisord.conf
This commit adds supervisor to manage raiden process within
testnet/mainnet raiden container.
> feat: restart raiden automatically testnet/mainnet

- init.sh
- setup.sh
- status.sh
This commit brings up the old status command since status2 is not fully ready (see #181)
> fix: restore old status command

- setup.sh
This closes #209.
This commit add empty checks after curl request to registry-1.docker.io
> feat: harden docker image metadata fetching

- images/litecoind/Dockerfile
- images/litecoind/entrypoint.sh
- setup.sh
- status2.sh
- xud-mainnet/docker-compose.yml
- xud-testnet/docker-compose.yml
> fix: litecoind corrupted data

- images/lnd/entrypoint.sh
- images/utils/args_parser.py
- images/utils/launcher/config/config.py
- images/utils/launcher/config/mainnet.conf
- images/utils/launcher/config/testnet.conf
- images/utils/launcher/node/bitcoind.py
- images/utils/launcher/node/lnd.py
Closes https://github.com/ExchangeUnion/xud-docker/issues/264
Testing instructions:
* `bash xud.sh -b neutrino --bitcoin-neutrino true`
* test if all xud ctl, status, getinfo, channel opening, swap work as expected
> feat: allow Neutrino on LND BTC

- images/utils/launcher/node/geth.py
- images/utils/launcher/node/lnd.py
- images/versions.ini
Closes #297 
@reliveyy could you build images for this PR too after it is merged?
> feat: update GETH and LND images

- tools/helper.py
This commit try to fix the master Travis build.
You can quick test it by checking this branch out and merge it to your local master then run
```
tools/push --dry-run --push-dirty
```
> fix: master travis build

- images/utils/launcher/node/__init__.py
- images/utils/launcher/node/image.py
This commit fixes broken logs, start, stop and restart commands.
Closes https://github.com/ExchangeUnion/xud-docker/issues/325
> fix: xudctl broken commands

- tools/helper.py
> fix: detect modified images

- tools/helper.py
This commit adds --no-cache option to build and push commands. This commit also fixes the problem when running build/push without .git directory it will create images without correspond git labels. So the newly built images will crash utils.
> feat: add --no-cache option

- images/utils/launcher/config/config.py
> fix: custom network dir

- tools/helper.py
This commit adds last modified commit into the unmodified history.
> fix: incremental build

- .travis.yml
- images/bitcoind/0.19.1/Dockerfile
- images/geth/1.9.12/Dockerfile
- images/litecoind/0.17.1/Dockerfile
- images/lnd/0.8.2-beta-simnet/Dockerfile
- images/lnd/0.9.0-beta-ltc/Dockerfile
- images/lnd/0.9.2-beta/Dockerfile
- images/ltcd/0.20.1-beta-simnet/Dockerfile
- images/raiden/0.100.5a1.dev162-2217bcb-simnet/Dockerfile
- images/raiden/0.100.5a1.dev162-2217bcb/Dockerfile
- images/utils/Dockerfile
- images/xud/1.0.0-beta.1-simnet/Dockerfile
- images/xud/1.0.0-beta.1-simnet/Dockerfile.aarch64
- images/xud/1.0.0-beta.1/Dockerfile
- images/xud/1.0.0-beta.1/Dockerfile.aarch64
Nothing exciting. Just updating the alpine base image
The build should be working now thanks to: #365
> chore: update base images

- images/lnd/0.9.0-beta-ltc/entrypoint.sh
- images/lnd/0.9.2-beta/entrypoint.sh
Related to #368 
This PR adds seed nodes for Bitcoin Neutrino that are hosted by us
> fix: update Neutrino seed nodes

- images/utils/launcher/node/image.py
> fix: 'Image' object has no attribute 'digest'

- images/utils/launcher/node/geth.py
> fix: broken geth attach

- tools/helper.py
This commit is the first step to link Discord xud-docker-bot messages with corresponding Travis builds.
> feat: add travis build url label

- tools/helper.py
This PR fixes modified images detection when there are uncommited or unstaged changes in current project workspace.
*(updated)*
**How to test this PR?**
1. Clone this repo
2. Checkout to this PR's branch
3. Make some changes to some images (do NOT `git add` or commit)
4. Run `tools/build` you should see `HEAD`
> chore(tools): fix git HEAD handling logic

- setup.sh
I verified the the problem was that docker pull either needs to be run as sudo or there needs to be a privileged docker group. It was not a docker-engine issue, I just had a weird docker install.
> improved error message

- images/lnd/0.9.0-beta-ltc-patched/Dockerfile
- images/lnd/0.9.0-beta-ltc-patched/entrypoint.sh
- images/lnd/0.9.2-beta-patched/entrypoint.sh
- images/utils/launcher/__init__.py
- images/utils/launcher/auto_unlock.py
- images/utils/launcher/check_wallets.py
- images/utils/launcher/config/config.py
- images/utils/launcher/node/__init__.py
- images/utils/launcher/node/base.py
- images/utils/launcher/node/lnd.py
- images/utils/launcher/node/xud.py
- images/xud/latest/entrypoint.sh
This prevents the 2h syncs on simnet which some of us experienced. Normal sync time until channels are active should be 15 minutes.
> apply create/restore flow for simnet

- xud.sh
> more informative error message

- tools/helper.py
This PR adds two labels (com.exchangeunion.application.branch, com.exchangeunion.application.revision) to all the images. We can use these two labels to tell if the upstream repository changed or not even there is no changes in xud-docker repository.
Modify any branches in ExchangeUnion/xud repository then xud-docker should auto-build any related branches. E.g. If new commits pushed to xud master then xud-docker master build will be auto triggered.
> chore: refine tools scripts to build xud:latest in time

- images/utils/launcher/node/image.py
> No redundant images pulling during light setup

- tools/helper.py
This PR fixes the none error when building xud:1.0.0-beta.2.
Run `tools/build xud:1.0.0-beta.2`. The expected result should be no error printed on the screen.
> fix: add a fallback plan to get xud revision and branch

- images/lnd/0.10.0-beta-simnet/Dockerfile
- images/lnd/0.10.0-beta/Dockerfile
- images/lnd/0.9.0-beta-ltc-simnet/Dockerfile
- images/lnd/0.9.0-beta-ltc/Dockerfile
Attempt to solve https://github.com/ExchangeUnion/xud-docker/issues/471
> downgrade go for lnd's to 1.13

- images/utils/launcher/check_wallets.py
Fixes https://github.com/ExchangeUnion/xud-docker/issues/486
> fix: 2nd launch stuck

- images/utils/launcher/node/base.py
> api calls will now time out

- images/utils/launcher/config/config.py
- images/utils/launcher/config/mainnet.conf
- images/utils/launcher/config/testnet.conf
- images/utils/launcher/node/geth.py
This PR adds `cache` option in network.conf geth section.
Closes #258
> feat: add geth cache option in network.conf

- images/utils/launcher/check_wallets.py
- images/utils/launcher/config/config.py
- images/utils/launcher/config/loader.py
This PR will remove the conf file auto creation when it is missing.
Closes #263
> feat(launcher): do not create conf file if missing

- images/utils/launcher/node/__init__.py
- images/utils/launcher/node/lnd.py
> chore(xudctl): avoid lnd status "Ready" with percentage

- images/xud/1.0.0-beta.3/entrypoint.sh
This should fix `xud.conf` for connext mainnet to work.
Test with default setup running `bash xud.sh -b fix/xud-conf-connext-mainnet`
> fix(xud): xud.conf disable raiden, enable connext

- images/utils/launcher/config/config.py
- images/utils/launcher/config/mainnet.conf
- images/utils/launcher/config/simnet.conf
- images/utils/launcher/config/template.py
- images/utils/launcher/config/testnet.conf
- images/utils/launcher/node/__init__.py
- images/utils/launcher/node/arby.py
- images/utils/launcher/node/base.py
- images/utils/launcher/node/image.py
This PR adds 4 arby related command-line options:
* `--arby.disabled`
* `--arby.binance-api-key`
* `--arby.binance-api-secret`
* `--arby.margin`
```
bash setup.sh -b disabled-option --arby.disabled
bash setup.sh -b disabled-option --arby.binance-api-key abc --arby.binance-api-secret 123 --arby.margin 0.001
```
> feat(arby): add disabled option

- images/arby/latest/Dockerfile
- images/arby/latest/Dockerfile.aarch64
This PR upgrades arby to latest master.
> upgrade arby

- tools/core/application_metadata/__init__.py
- tools/core/application_metadata/arby.py
- tools/core/github.py
Create a new branch in xud-docker and modify arby Dockerfile to build some dummy branch. If you push to dummy branch then Travis build will be auto-triggered.
> tools: add arby application revision/branch detection

- README.md
Closes https://github.com/ExchangeUnion/xud-docker/issues/547
> chore: add python 3.8 as build requirement

- images/utils/launcher/node/__init__.py
- images/utils/launcher/node/base.py
- images/utils/launcher/node/connext.py
This PR keeps align with xud getinfo connext status.
Closes #512.
> chore(xudctl): refine connext status

- images/connext/latest/Dockerfile
- images/connext/latest/Dockerfile.aarch64
- images/utils/launcher/node/connext.py
This PR upgrades connext to 7.0.0.alpha6 and changes the simnet node URL to use the new simnet node.
> upgrade connext to 7.0.0.alpha6

- images/utils/launcher/node/xud.py
> chore(xud): add NODE_ENV=production

- tools/core/application_metadata/__init__.py
- tools/core/application_metadata/arby.py
- tools/core/application_metadata/boltz.py
- tools/core/application_metadata/xud.py
- tools/core/github.py
- tools/core/image.py
Reopen https://github.com/ExchangeUnion/xud-docker/pull/549
> tools: add boltz application revision/branch detection

- images/lnd/entrypoint-simnet.sh
The recent Tor address waiting in simnet lndbtc is becuase my messed-up copied entrypoint.sh for it.
> fix: simnet lndbtc

- images/connext/src.py
- images/utils/launcher/config/template.py
- images/utils/launcher/node/connext.py
- mainnet: 7.0.0-alpha.14 -> 7.0.0
- new indra node urls
> Enable connext mainnet

- images/utils/launcher/config/template.py
Closes https://github.com/ExchangeUnion/market-maker-tools/issues/56
> chore: upgrade arby 0.2.0 -> 1.0.0

- images/utils/launcher/config/template.py
update mainnet to `xud:1.0.0-beta.7`
tag mainnet utils `20.07.27`
`.build xud:1.0.0-beta.7` done: https://travis-ci.org/github/ExchangeUnion/xud-docker/jobs/712236898
> chore: upgrade xud:1.0.0-beta.6 -> beta.7

- images/bitcoind/src.py
- images/utils/launcher/config/template.py
Let's do some sanity swaps with this on testnet just to make sure lnd is fine with this version @raladev
> chore: upgrade bitcoind 0.20.0 -> 0.20.1

- images/utils/launcher/config/template.py
simnet and testnet were already upgraded a while ago and no problems were reported.
> chore: upgrade geth 1.9.17 -> 1.9.18 on mainnet.

- images/connext/src.py
Connext client version update for latest tag
Required for https://github.com/ExchangeUnion/xud/pull/1783
> Update connect commit hash for latest version

- images/webui/supervisord.conf
> feat: auto restart webui

- images/webui/entrypoint.sh
> feat: btc_usdt pair first

- images/geth/src.py
- images/utils/launcher/config/template.py
Upgrading to https://github.com/ethereum/go-ethereum/releases/tag/v1.9.20
> chore: upgrade geth 1.9.19 -> 1.9.20

- images/boltz/wrapper.sh
- images/utils/launcher/__init__.py
Closes https://github.com/ExchangeUnion/xud-docker/issues/688
> fix: more concise error message for Boltz on simnet

- tools/push
This is just a quick fix for current broken ARM builds. I'll open another PR when I found a better solution.
> tools: a crappy ARM fix

- images/connext/src.py
- images/utils/launcher/config/template.py
@raladev please help test all main connext functionality, I will test if it unbricks my mainnet environment from a state sync issue that is supposed to be fixed with this version
> chore: upgrade connext 1.3.1 -> 1.3.2

- images/utils/launcher/__init__.py
E.g.
* `deposit eth` -> `walletdeposit eth`
* `withdraw 100 usdt <addr> <fee>` -> `walletwithdraw 100 usdt <addr> <fee>`
> chore: delegate deposit/withdraw to xucli when currency is not btc/ltc

- images/utils/launcher/__init__.py
- images/utils/launcher/node/__init__.py
- images/utils/launcher/node/image.py
This PR reveals the real reason behind the error
```
Error: Timeout error: Couldn't connect to Docker to check for updates. Please check your internet connection and https://status.docker.com/.
```
Close https://github.com/ExchangeUnion/xud-docker/issues/700
- Checkout `image-not-found` branch
- Modify template.py
- `tools/build utils`
- `bash setup.sh -b image-not-found --dev`
> feat: reveal image not found error

- images/utils/launcher/check_wallets.py
> fix: backup location retry answer defualts to yes (#525)

- images/utils/launcher/config/template.py
- images/utils/launcher/node/connext.py
- images/utils/launcher/node/image.py
- images/xud/entrypoint.sh
- images/xud/src.py
This PR updates xud1-simnet branch to the latest changes from master + connext v2 version.
> Use connext-v2 for simnet xud1

- images/utils/launcher/check_wallets.py
- tests/integration/cli.txt
- tests/integration/test_light.py
Part of https://github.com/ExchangeUnion/xud/pull/2000
> chore: remove "YOU WILL NOT BE ABLE TO DISPLAY YOUR XUD SEED AGAIN."

- images/utils/launcher/docker/core.py
This commit refines the wall of conditional statements in `pull_image` function by adding some explanatory comments.
> refine the wall of conditional statements

- images/utils/launcher/config/template.py
- images/utils/launcher/node/connext.py
This PR enables connext vector for testnet and makes some preparations for mainnet.
> feat: enable connext testnet
