setup.sh
Closes https://github.com/ExchangeUnion/xud-docker/issues/70.
Still not sure what causes the additional white space on first run of the script and this solution is not very elegant, but fixes it for now.
=> fix: whitespace in network selection

images/xud/Dockerfile, images/xud/xud.conf, xud-simnet/docker-compose.yml
In this commit we expose xud's raiden hashresolver endpoint and specify
the exposed endpoint in raiden's configuration so that it knows where to
resolve external hashes.
=> fix: raiden hashresolver

xud-mainnet/docker-compose.yml, xud-testnet/docker-compose.yml
In this commit we're adding the missing raiden `resolver-endpoint` config flag to testnet and mainnet.
=> fix(raiden): add missing resolver-endpoint config

status.sh
Closes #110
Looks like the `printf: 4.34000000000000000000: invalid number` errors were caused by an invalid locale (for example `LC_NUMERIC=de_AT.UTF-8`) that doesn't know how to handle these numbers that use a dot instead of a comma.
=> fix: set LC_NUMERIC for printing sync percentage

images/xud-simnet/entrypoint.sh, images/xud/entrypoint.sh
This PR removes the logic that handles setting the default currencies and pairs for simnet. This logic is now redundant as it will be handled on xud level.
=> chore: remove default currencies and pairs logic

images/lnd/Dockerfile
This PR enables the `invoicesrpc` of LND that is required to generate HOLD invoices which are needed for the swaps of XUD.
=> fix: enable invoicesrpc in LND

images/versions.ini, xud-mainnet/docker-compose.yml, xud-testnet/docker-compose.yml
This PR updates the Bitcoin Core version to `0.18.1`. The latest LND version supports this Bitcoin Core version, therefore this update is possible now
=> chore: update Bitcoin Core version

xud-mainnet/docker-compose.yml, xud-testnet/docker-compose.yml
this adds the flag --cache=1024 to geth for testnet & mainnet. 1024 is the [default value](https://geth.ethereum.org/interface/Command-Line-Options) and the reason to add this flag is to point users to it from the docs to manually change this value for a faster sync
=> feat: this adds the flag --cache=1024 to geth for testnet & mainnet

xud-mainnet/docker-compose.yml, xud-testnet/docker-compose.yml
This commit re-adds missing docker-compose config that was accidentally
removed in https://github.com/ExchangeUnion/xud-docker/commit/d4ce1a3bf5f7e39da0a79d4fade412d0cc6831d7
=> fix: missing docker-compose config

images/xud/proxychains4.conf
This commit fixes an issue where `xucli create` didn't output: `The keystore for raiden was initialized.` because `xud` caught a stderr warning from `proxychains`.
It couldn't proxy requests made by `seedutil` child process.
=> fix: create raiden keystore output

images/raiden/entrypoint.sh, images/xud/entrypoint.sh, images/xud/xud.conf, xud-mainnet/docker-compose.yml, xud-testnet/docker-compose.yml
This commit moves the keystore file generated by xud's seedutil to
raiden's data directory `$network/data/raiden/keystore`.
Steps to test:
`bash xud.sh -b raiden-keystore-improvements`
=> chore: move raiden keystore

images/lnd/entrypoint.sh
This commit adds a check to avoid rewriting lnd's configuration file if it already exists.
=> fix: do not rewrite config for lnds

images/versions.ini, xud-mainnet/docker-compose.yml, xud-testnet/docker-compose.yml
This PR updates GETH to the latest version: [Elasa (v1.9.6)](https://github.com/ethereum/go-ethereum/releases/tag/v1.9.6)
*Doesn't have to be merged before tagging the first release*
=> chore: update GETH to v1.9.6

init.sh
Resolves #180
The original `sed -n '1!p'` way to hide first warning line is not working with interactive command like unlock/create because sed print each line when `\n` is read. So inline prompt won't display until the user type Enter.
This PR replace sed with `while read...` to handle output of xucli character by character to solve the AFTER prompt problem.
=> fix: xucli unlock

images/geth/entrypoint.sh, setup.sh, xud-mainnet/docker-compose.yml, xud-testnet/docker-compose.yml, xud.sh
This closes #202.
This commit adds 3 new command line options `--bitcoind-dir`, `--litecoind-dir` and `--geth-dir` to customize corresponding services' data directories. The implementation uses environment variables before `docker-compose` command to inject variables into docker-compose file.
**ATTENTION!** This commit updates `xud.sh` becuase `getopts` takes `--bitcoind-dir` as `-b<branch>`
Updates:
* `--geth-chaindata-dir`
=> feat: customize bitcoind, litecoind and geth data directories

images/versions.ini, xud-mainnet/docker-compose.yml, xud-testnet/docker-compose.yml
Closes #228 
This PR updates GETH to version `v1.9.7`. The only change relevant to us is:
> This release is a bit more special, however, as it finally initializes the Ethereum mainnet Istanbul fork block 9069000, targeted to arrive around the 4th of December!
=> chore: update GETH to v1.9.7

images/versions.ini, xud-mainnet/docker-compose.yml, xud-testnet/docker-compose.yml
This PR updates GETH to version `v1.9.8`. The only change in this version relevant to our Docker setup is: `replacing the trie cacher, slashing memory consumption on mainnet - using default configs - by 1GB`.
[Full release notes](https://github.com/ethereum/go-ethereum/releases/tag/v1.9.8)
=> chore: update GETH to v1.9.8

images/geth/entrypoint.sh
This closes https://github.com/ExchangeUnion/xud-docker/issues/244
I just comment out `--bootnodes` and let us see if it solves the problem. Then we will try to add a fallback plan to guarantee there are peers in most cases.
=> fix: geth mainnet peers

images/utils/config_parser.py, images/utils/launcher/config/xud-docker.conf
This commit will reveal xud-docker.conf parsing errors. The reason why <network>-dir is not working in xud-docker.conf is because we use "load" function which takes the file content as the filename.
Closes https://github.com/ExchangeUnion/xud-docker/issues/280
=> fix: <network>-dir not working in xud-docker.conf

images/bitcoind/Dockerfile.aarch64, images/geth/Dockerfile.aarch64, images/geth/entrypoint.sh, images/litecoind/Dockerfile.aarch64, images/lnd-simnet/Dockerfile.aarch64, images/lnd/Dockerfile.aarch64, images/ltcd-simnet/Dockerfile.aarch64, images/raiden-simnet/Dockerfile.aarch64, images/utils/launcher/node/base.py, images/xud-simnet/Dockerfile.aarch64, images/xud/Dockerfile.aarch64, supports/Dockerfile.aarch64, supports/install.sh, tools/helper.py
This commit enhanced tools/build command with --platform option. You can use this option to build the image on specific architecture like "linux/arm64". And if there is another Dockerfile with some suffixes like aarch64, armhf, pppc64le, s390x, solaris and windows, tools/build will use a corresponding Dockerfile according to your --platform value.
How to test this PR?
- Clone this repository and checkout feat/arm branch
- Ensure that you have installed [buildx plugin](https://docs.docker.com/buildx/working-with-buildx/) for Docker
- Run `tools/build --platform linux/arm64`
Closes https://github.com/ExchangeUnion/xud-docker/issues/257
=> feat: build all images on aarch64 architecture

images/utils/launcher/node/geth.py, images/versions.ini
Obligatory GETH update PR
Testing instructions:
* `bash xud.sh -b update-geth-1910`
* test if raiden and swaps still work
=> chore: update GETH to v1.9.10

images/utils/launcher/check_wallets.py
This commit strictly matches the choice number. Before this we will enter into the second choice when this reply is not "1". This could surprise the user somehow.
=> fix: create/restore choice strict match

images/xud/1.0.0-beta.1-simnet/Dockerfile, images/xud/1.0.0-beta.1-simnet/Dockerfile.aarch64, images/xud/1.0.0-beta.1/Dockerfile, images/xud/1.0.0-beta.1/Dockerfile.aarch64
This commit shrink xud image size from ~600M to 150M. The image size blows up becuase the seedutil/go build folder is included in the final image.
=> fix: xud image size

images/utils/launcher/config/mainnet.conf, images/utils/launcher/config/testnet.conf
This commit adds `mode` config option to bitcoind, litecoind and geth node. And it deprecates `external` and `neutrino` options.
Closes #295
=> feat: add mode config option

images/utils/launcher/__init__.py, images/utils/launcher/close_other_utils.py, setup.sh
This commit adds a number suffix to utils container name. It will auto calculate the number which is the maximum existing number plus one. And there is an interactive question before launching xudctl shell. It will prompt you like:
Found 2 existing xud ctl sessions. Do you want to close these? [Y/n] Y
Stopping mainnet_utils_1...
Stopping mainnet_utils_2...
Removing mainnet_utils_1...
Removing mainnet_utils_2...
Closes #260
=> fix: name collision when running multiple utils containers

images/geth/1.9.12/entrypoint.sh, images/utils/launcher/config/config.py, images/utils/launcher/node/geth.py
This PR fixes a typo which causes KeyError: 'container_dir' when using custom geth ancient chaindata dir.
Closes https://github.com/ExchangeUnion/xud-docker/issues/392
=> fix: two typos which cause geth custom dir not working

images/utils/launcher/node/__init__.py, images/utils/launcher/node/bitcoind.py, images/utils/launcher/node/btcd.py, images/utils/launcher/node/geth.py, images/utils/launcher/node/lnd.py, images/utils/launcher/node/raiden.py, images/utils/launcher/node/xud.py
=> better status messages

tools/helper.py
This PR fixes tools scrips which build all images in every Travis build since last `xud-latest` PR merged into master.
=> fix: master building all images

.travis.yml, tools/helper.py
This PR changes old travis build flow from
```
1) build foo__x86_64 and foo__aarch64
2) create foo including amd and arm
```
to
```
build foo__x86_64 and create manifest list including amd and arm or amd only
build foo__aarch64 and create manifest list including amd and arm or arm only
```
=> chore: push manifest list incrementally

tools/helper.py
```
Traceback (most recent call last):
File "tools/helper.py", line 188, in get_github_branch_revision
r = urlopen(f"https://api.github.com/repos/{repo}/git/refs/heads/{branch}")
File "/opt/python/3.8.0/lib/python3.8/urllib/request.py", line 222, in urlopen
return opener.open(url, data, timeout)
File "/opt/python/3.8.0/lib/python3.8/urllib/request.py", line 531, in open
response = meth(req, response)
File "/opt/python/3.8.0/lib/python3.8/urllib/request.py", line 640, in http_response
response = self.parent.error(
File "/opt/python/3.8.0/lib/python3.8/urllib/request.py", line 569, in error
return self._call_chain(*args)
File "/opt/python/3.8.0/lib/python3.8/urllib/request.py", line 502, in _call_chain
result = func(*args)
File "/opt/python/3.8.0/lib/python3.8/urllib/request.py", line 649, …
```
=> fix arm64 build failure

images/utils/launcher/node/btcd.py, images/utils/launcher/node/lnd.py, images/utils/launcher/node/raiden.py
This commit changes the btcd/ltcd simnet ip to use a domain instead so
that in case of the ip change only the DNS entry needs to be updated.
Test:
```
bash xud.sh -b chore/use-domain-for-btcd-ltcd
```
...and ensure that BTC/LTC simnet chains are working.
=> chore: change btcd/ltcd server ip to domain

README.md
Update link from 
https://docs.exchangeunion.com/start-trading/user-guide
to
https://docs.exchangeunion.com/start-earning/market-maker-guide#the-setup
since market makers are the target user group of xud-docker
=> chore: update xud-docker link to docs

tools/helper.py
This PR update master git diff base hash to the most recent commit so the build won't have a long commit history to handle (accelerating master build).
=> chore(tools): update master git diff hash

images/utils/launcher/node/__init__.py, images/utils/launcher/shell/shell.py
This PR adds a confirmation question before xudctl `down` command.
```
Are you sure to shutdown your xud environment (this will cancel all open orders)? [Y/n]
```
Closes #304
=> feat(xudctl): add confirmation before down command

images/utils/launcher/__init__.py, images/utils/launcher/config/config.py, images/utils/launcher/errors.py
Closes #252
**Examples:**
```
❌ Failed to parse command-line arguments, exiting.
Error details: unrecognized arguments: --foo
❌ Failed to parse config file /home/yy/.xud-docker/xud-docker.conf, exiting.
Error details: Found invalid character in key name: '*'. Try quoting the key name. (line 4 column 4 char 106)
❌ Failed to parse config file /home/yy/.xud-docker/simnet/simnet.conf, exiting.
Error details: Found invalid character in key name: '$'. Try quoting the key name. (line 37 column 3 char 1014)
```
=> chore(launcher): refine config parsing errors

images/utils/launcher/node/lnd.py
This PR fixes lnd status timeout which is caused by retrieving all logs of lnd. It retrieves last 1 hour logs of lnd instead.
Closes #510.
=>  fix(xudctl): lnd status timeout

images/utils/launcher/config/config.py, images/utils/launcher/config/template.py, images/utils/launcher/node/image.py, setup.sh
EDIT: this removes the faulty timestamp comparison for the local xud-docker setup to check if a local image needs to be updated with a newer available image in the docker cloud. It now follows the simple principle of *only* comparing mage hashes (digests). If the hash in the docker cloud is **different**, it prompts to to update.
The following pseudo code describes the behavior:
```
if can't get hash from cloud
retry (don't return null) up until 30s timeout
if can't get hash from local:
local.digest=null (new environment)
if local.hash == cloud.hash:
return "UP_TO_DATE"
else:
pull
```
=> chore: remove image timestamp comparison

tools/core/image.py, tools/core/toolkit.py, tools/helper.py
This PR adds option `-f` and `--force` to `tools/build` command. 
The redundant image pulling and tagging are also removed in this PR. See https://github.com/ExchangeUnion/xud-docker/pull/546/files#diff-8a792fef7c99bb820b9a2bbfe2d0d532L207-L212
=> tools: forcefully build without manifest checking

images/lnd/0.10.1-beta-simnet/Dockerfile, images/lnd/0.9.0-beta-ltc-simnet/Dockerfile, images/utils/launcher/node/lnd.py
Finally:
```
kilrau@raspixud:~$ docker logs -f simnet_lndbtc_1 | grep autopilot
2020-06-19 10:38:19.251 [INF] ATPL: Instantiating autopilot with active=false, max_channels=5, allocation=0.600000, min_chan_size=20000, max_chan_size=4294967295, private=false, min_confs=1, conf_target=3
```
lndltc still activates it though and it's not obvious why since config is 1:1 with lndbtc, so I hope this will be fixed with upgrade to 0.10.1:
```
kilrau@raspixud:~$ docker logs -f simnet_lndltc_1 | grep autopilot
2020-06-19 10:38:17.834 [INF] ATPL: Instantiating autopilot with max_channels=5, allocation=0.600000, min_chan_size=20000, max_chan_size=4294967295, private=false, min_confs=1, conf_target=3
```
=> Disable autopilot on simnet lnds

tools/core/image.py
This PR fixes the bug when cloud image has no application.revision label then "skip build" test will returns True.
=> tools: fix application metadata checking logic

images/utils/launcher/__init__.py
This PR adds two shortcut commands for boltzcli
* `deposit btc/ltc ...` (`boltzcli btc/ltc deposit ...`)
* `withdraw btc/ltc ...` (`boltzcli btc/ltc withdraw ...`)
Closes #565
=> chore(boltz): add shortcuts for boltzcli deposit/withdraw

images/utils/launcher/config/config.py, images/utils/launcher/config/mainnet.conf, images/utils/launcher/config/simnet.conf, images/utils/launcher/config/testnet.conf, images/utils/launcher/node/arby.py
This PR adds a new configuration `live-cex` option to arby which enables:
- fetching real balances from a centralized exchange
- executing market buy and sell orders on CEX after a successful swap
The minimum for buy/sell orders is 0.005 ETH.
To enable live CEX mode:
```
[arby]
#live-cex="true"
#binance-api-key = "your api key"
#binance-api-secret = "your api secret"
```
Test:
`bash xud.sh -b arby/live-mode`
=> feat: add arby live CEX mode option

images/connext/latest/Dockerfile, tools/core/application_metadata/common.py
This PR fixed a common error when building connext "reference not found in the tree". It's because we only clone 2 depth of the connext repository and we checkout the commit more than 2 commits before its latest HEAD. This PR also fixed `get_application_metadata` function "index out of array" error. It becuase when building connext `git checkout` will result in `git show HEAD` only shows reference name `HEAD` which we cannot infer the branch from.
=> tools: fix connext build

images/utils/launcher/config/config.py, images/utils/launcher/config/mainnet.conf, images/utils/launcher/config/simnet.conf, images/utils/launcher/config/template.py, images/utils/launcher/config/testnet.conf, images/utils/launcher/node/__init__.py, images/utils/launcher/node/webui.py, images/webui/latest/Dockerfile, images/webui/latest/Dockerfile.aarch64, images/webui/latest/entrypoint.sh, images/webui/latest/supervisord.conf, images/xud/latest/entrypoint.sh, requirements-dev.txt
This PR adds xud-webui-poc (ReactJS based frontend) and xud-socketio (NodeJS based backend) into one container `webui`. And the container will expose port 8080 to your host. The frontend app uses REST + Websocket (socketio) API to get the order book of different trading pairs. The backend server translates the REST + Websocket API to gRPC calls and send it back to xud container.
Run `bash setup.sh -b webui --webui`, then you should see a web UI in http://localhost:8080 like below. And it will auto-update when orders changed.
EDIT: closes https://github.com/ExchangeUnion/xud/issues/1495, closes https://github.com/ExchangeUnion/xud/issues/1661
=> feat: add webui

.travis.yml, tools/build, tools/build.bat, tools/core/__init__.py, tools/core/docker.py, tools/core/git.py, tools/core/image.py, tools/core/src.py, tools/core/toolkit.py, tools/helper.py, tools/push, tools/push.bat, tools/release, tools/release.bat, tools/test, tools/test.bat
This commit fixes the overlapped imported src module when building multiple images. And we replaced `--cross-build` with `--platform`. You can specify more than one platform with multiple `--platform` options like `--platform linux/amd64 --platform linux/arm64`. If no `--platform` specified, then the current platform will be used. This commit also simplifies the output with `Build image:tag (arch)` message only. You can see more building details from tools/tools.log.
```
tools/build -f xud arby:0.2.0
```
=> tools: fix building multiple images

tools/core/image.py
>   File "/home/travis/build/ExchangeUnion/xud-docker/tools/core/image.py", line 151, in _skip_build
assert application_revision, "application revision should not be None"
>  AssertionError: application revision should not be None
=> tools: fix utils build

images/webui/entrypoint.sh, images/webui/src.py
This PR updates `webui:1.0.0` image backend to v1.1.0. So the new `--pairs-weight` option will be available. We use this option to reorder the frontend trading pairs from
```
ltc_btc, eth_btc
```
to
```
eth_btc, ltc_btc
```
Wait for new `webui:1.0.0` pushed.
```
bash xud.sh --webui.disabled=false
```
1. Select Mainnet
2. Clean up your browser local storage on http://localhost:8888. 
3. You should see `ETH/BTC` show up by default.
=> feat(webui): reorder pairs (eth_btc, ltc_btc)

images/arby/supervisord.conf
Previously supervisor would restart arby only if the exit code was unexpected (non 0). This PR changes it so that regardless of the exit code the process will be restarted.
=> feat(arby): restart when exit code 0

images/connext/src.py
This PR upgrades connext latest and and 7.1.2 commit hash. The new commit contains an important bug fix that prevents from duplicate clients from initializing.
=> feat: update connext latest and 7.1.2 commit hash

images/utils/launcher/__init__.py, images/utils/launcher/config/config.py, setup.sh
This PR refines `--help` option ouptut and adds `help` command to xud-ctl shell.
Resolves #369 
```
bash xud.sh -b big-help --help
```
```
bash xud.sh -b big-help
network > help
```
=> feat: all-in-one help

images/xud/entrypoint.sh
This PR remove "[entrypint]" from xud image /etc/hosts file.
```bash
bash xud.sh
docker exec simnet_xud_1 cat /etc/hosts
bash xud.sh -b fix-xud-hosts
docker exec simnet_xud_1 cat /etc/hosts
```
=> fix: xud image hosts file

images/utils/launcher/__init__.py, images/utils/launcher/node/DockerTemplate.py, images/utils/launcher/node/__init__.py, images/utils/launcher/node/base.py
This PR implement a very simple fix for update decline by just bypassing ensuring all services are up and running and any post actions. If the user declines the update he will enter into the xud-ctl shell directly.
The edge cases:
1. If the new setup removes some image and it is stopped or removed in current environment, then there is no way to bring it back automatically. And on the other side, if the new setup removes some service but the old setup keep it running, then this service needs to manually stop and remove.
2. If your setup is up-to-date then you will use the new utils (setup) to ensure all services are up and do post actions. This could be error prone.
**UPDATE**
A significant change was made in "preview! fix false update (down/up case)" which introduced a new concept …
=> fix: update decline in a simple way

images/utils/launcher/config/template.py
Updates boltz-lnd on mainnet to [`v1.1.1`](https://github.com/BoltzExchange/boltz-lnd/releases/tag/v1.1.1) which fixes https://github.com/BoltzExchange/boltz-lnd/issues/19
=> chore: update boltz to v1.1.1 on mainnet

images/proxy/Dockerfile, images/proxy/entrypoint.sh, images/proxy/src.py, images/utils/launcher/config/config.py, images/utils/launcher/config/mainnet.conf, images/utils/launcher/config/simnet.conf, images/utils/launcher/config/template.py, images/utils/launcher/config/testnet.conf, images/utils/launcher/node/__init__.py, images/utils/launcher/node/proxy.py, setup.sh
This PR adds `--api` optinon for xud-docker-api poc #725
```bash
bash xud.sh -b api --proxy.disabled=false
curl localhost:8080/api/v1/xud/getinfo
```
The default API ports for different networks
1. simnet: 8080 (changed to 28889)
2. testnet: 8081 (changed to 18889)
3. mainnet: 8082 (changed to 8889)
=> feat: add xud-docker api

images/arby/src.py, images/utils/launcher/config/config.py, images/utils/launcher/config/mainnet.conf, images/utils/launcher/config/simnet.conf, images/utils/launcher/config/template.py, images/utils/launcher/config/testnet.conf, images/utils/launcher/node/arby.py, setup.sh
This PR renames arby's `opendex-baseasset` and `opendex-quoteasset` back to `baseasset` and `quoteasset`.
Additionally, if `cex-baseasset` or `cex-quoteasset` is not specified the value of `baseasset` and `quoteasset` will be used by default.
=> feat: change arby config

images/utils/launcher/__init__.py, images/utils/launcher/check_wallets.py, images/utils/launcher/config/config.py, images/utils/launcher/config/template.py, images/utils/launcher/node/__init__.py, images/utils/launcher/node/base.py, images/utils/launcher/node/geth.py, images/utils/launcher/node/image.py, images/utils/launcher/utils.py
This PR dumps all configurations as `network_dir/logs/config.sh` on every launch. The dump file could be used to distinguish disabled services and missing containers.
```bash
bash xud.sh -b dump-config
cat ~/.xud-docker/{simnet,testnet,mainnet}/logs/config.sh
```
=> feat: dump config

images/proxy/Dockerfile, images/proxy/entrypoint.sh, images/proxy/src.py, images/utils/Dockerfile, images/utils/launcher/config/config.py, images/utils/launcher/config/template.py, images/utils/launcher/node/image.py, images/utils/launcher/node/proxy.py, xud.sh
This PR updates proxy image with `status` branch of [xud-docker-api-poc](https://github.com/exchangeunion/xud-docker-api-poc) which add status API for each services.
```
bash xud.sh -b status-api --proxy.disabled=false
curl -s localhost:18889/api/v1/status
```
You should got a JSON response like
```json
{"arby":"Container missing","bitcoind":"Ready (light mode)","boltz":"Ready","connext":"Ready","geth":"Ready (light mode)","litecoind":"Ready (light mode)","lndbtc":"Ready","lndltc":"Ready","webui":"Container missing","xud":"Waiting for channels"}
```
=> feat: add status api

images/utils/launcher/__init__.py
Right now `deposit btc` forwards the request to boltz-cli but `deposit BTC` (and all chains that are not all lower case) to xud. Same for `withdraw`
=> fix: boltz cli for not lowercase chain

images/arby/Dockerfile, images/bitcoind/Dockerfile, images/boltz/Dockerfile, images/connext/Dockerfile, images/geth/Dockerfile, images/litecoind/Dockerfile, images/lndbtc-simnet/Dockerfile, images/lndbtc/Dockerfile, images/lndltc-simnet/Dockerfile, images/lndltc/Dockerfile, images/utils/launcher/node/image.py, images/webui/Dockerfile, images/webui/Dockerfile.aarch64, images/xud/Dockerfile, images/xud/Dockerfile.aarch64
Would want to wait with node.js upgrade to 14 until @sangaman  made sure xud is v14 compatible. Main reason for the upgrade to alpine 3.12 is the upgraded tor version.
=> chore: upgrade alpine 3.11 -> 3.12, go1.13 -> go1.14

.github/workflows/ci.yml, README.md, tools/build, tools/core/docker.py, tools/core/image.py, tools/core/toolkit.py, tools/helper.py, tools/push
This PR adds GitHub actions to this project. It also
- Reduce tools scripts minimum Python version requirement (3.8 -> 3.7)
- Bring back no images version `tools/build` and `tools/push`. Simply build images from `git diff` for every push
```
git diff --name-only $(git merge-base --fork-point origin/master)..HEAD images
```
=> ci: use GitHub actions

.github/workflows/auto-build.yml, .github/workflows/manual-build.yml, tools/core/image.py, tools/core/utils.py
This PR adds `com.exchangeunion.image.ci` label to images built from GitHub actions. So the xud-docker-bot could tell the image build source like Travis.
=> tools: add ci label to images

images/proxy/Dockerfile, images/proxy/src.py
This PR adds the functionality of serving the XUD Explorer Dashboard as a web application, independent of the the native Electron app, from the proxy container.
Closes https://github.com/ExchangeUnion/xud-ui/issues/94
How to test:
in `xud-docker` dir
```bash
git checkout feat/proxy-ui
```
edit `images/proxy/src.py` by replacing `"master"` with `"feat/ui"`. The frontend branch can remain as `"main"`.
```bash
./tools/build proxy:latest
./tools/build utils:latest
bash setup.sh -b feat/proxy-ui --proxy.disabled=false --dev --use-local-images proxy
```
Open `http://localhost:{port}` in the browser (the port is the usual proxy port 8889, 18889, 28889 depending on the network)
=> feat(proxy): add ui dashboard app to proxy container

tools/core/toolkit.py
This PR fixes master auto-build when a feature branch merged in. There is no modified images detected because on master branch
```
git diff --name-only $(git merge-base --fork-point origin/master)..HEAD images
```
equals to
```
git diff --name-only HEAD..HEAD images
```
which will result in an empty diff set for sure. This PR fixes it by using another diff command on master
```
git diff --name-only HEAD^..HEAD images
```
It diffs with one commit before. I know this is not a perfect solution but it's the easiest way and covers most cases especially when we following "Squash and merge" practice for all PRs.
=> tools: fix master auto-build when a feature branch merged

images/utils/launcher/config/template.py
This version upgrades arby to 1.3.1 which mitigates memory leakage by reducing the restart interval from 6 hours to 1 hour.
=> feat: upgrade arby to 1.3.1

images/proxy/Dockerfile, images/proxy/entrypoint.sh, images/proxy/src.py, images/utils/launcher/config/template.py
This PR bump proxy frontend to `feat/console` branch and backend to `console` branch to present the console view + api. And it also makes proxy container enabled by default.
```
bash xud.sh -b console
```
N.B. Use `mkcert` to trust your self-signed certificate
```bash
mkcert -install
mkcert localhost 127.0.0.1 ::1 -cert-file tls.crt -key-file tls.key
sudo mkdir -p ~/.xud-docker/simnet/data/proxy
sudo cp tls.* ~/.xud-docker/simnet/data/proxy
```
EDIT by @kilrau : closes https://github.com/ExchangeUnion/xud-docker/issues/745
EDIT by @kilrau : closes https://github.com/ExchangeUnion/xud-ui/issues/29
=> feat: add console api

images/utils/launcher/config/template.py
Updates boltz-lnd to [v1.1.2](https://github.com/BoltzExchange/boltz-lnd/releases/tag/v1.1.2) which includes a fix to show the Swap ID in the `DepositResponse`
=> chore: update boltz-lnd to v1.1.2

images/utils/launcher/docker/core.py
This is a hotfix for ARM when the error below happens
```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/__init__.py", line 281, in launch
env.start()
File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/__init__.py", line 250, in start
up_env = self.node_manager.update()
File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/node/__init__.py", line 233, in update
images = self.image_manager.check_for_updates()
File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/node/image.py", line 178, in check_for_updates
use, pull = f.result()
File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
return self.__get_result()
File …
```
=> fix: KeyError when retrieving Labels

images/arby/Dockerfile, images/connext/Dockerfile, images/xud/Dockerfile, images/xud/Dockerfile.aarch64
This updates node versions to use lts instead of hardcoding at v12. Lts is currently v14 which supports ES2020 language features like `bigint`.
This is dependent on https://github.com/ExchangeUnion/xud/pull/2035 being merged, as currently the sqlite version we use does not build properly with node v14.
=> chore: use node lts

images/boltz/Dockerfile, images/boltz/entrypoint.sh, images/boltz/wrapper.sh, images/utils/launcher/config/config.py, images/utils/launcher/config/template.py
This PR fixes the boltz-lnd integration because it was broken in the latest couple commits merged into master. These commits:
- added TLS to the gRPC interface
- added macaroon authentication to the gRPC interface
- added a REST proxy for the gRPC interface
Todo:
=> fix: boltz image after breaking gRPC changes

images/boltz/Dockerfile, images/boltz/entrypoint.sh, images/boltz/wrapper.sh, images/utils/launcher/config/template.py
This PR updates `boltz-lnd` to [v1.2.2](https://github.com/BoltzExchange/boltz-lnd/releases/tag/v1.2.2). In [v1.2.1](https://github.com/BoltzExchange/boltz-lnd/releases/tag/v1.2.1) and [v1.2.2](https://github.com/BoltzExchange/boltz-lnd/releases/tag/v1.2.2) there were no major changes but I removed the sample config from the repository and added the `--datadir` flag which should make the scripts in the container a little bit simpler.
@reliveyy I moved the macaroons (there are two now; admin and readonly) to a new folder: `$BOLTZ_DATADIR/macaroons`
=> chore: update boltz image to v1.2.2

setup.sh
This is the last release of xud-docker with **utils** image.
=> chore: release version 21.01.29
